import DashboardWidget, { IDashboardWidgetAttrs } from 'flarum/admin/components/DashboardWidget';
import Mithril from 'mithril';
import ItemList from 'flarum/common/utils/ItemList';
export default class HorizonStatsWidget extends DashboardWidget {
    loading: boolean;
    data: any;
    previousData: any;
    error: string | null;
    autoRefreshEnabled: boolean;
    autoRefreshInterval?: number;
    refreshInterval: number;
    lastRefreshTime?: number;
    oncreate(vnode: Mithril.Vnode<IDashboardWidgetAttrs>): void;
    onremove(): void;
    loadHorizonStats(): Promise<void>;
    toggleAutoRefresh(enabled: boolean): void;
    setAutoRefresh(): void;
    setRefreshInterval(interval: number): void;
    clearAutoRefresh(): void;
    className(): string;
    content(): JSX.Element;
    renderLastRefresh(): JSX.Element | null;
    renderRefreshIntervalSelector(): JSX.Element;
    renderHealthIndicator(): JSX.Element | null;
    renderStatsSection(): JSX.Element;
    renderStat(label: Mithril.Children, value: string, infoLabel?: Mithril.Children, infoUrl?: string, metricKey?: string): JSX.Element;
    statItems(label: Mithril.Children, value: string, infoLabel: Mithril.Children | undefined, infoUrl: string | undefined, metricKey?: string): ItemList<Mithril.Children>;
    labelItems(label: Mithril.Children, infoLabel: Mithril.Children | undefined, infoUrl: string | undefined): ItemList<Mithril.Children>;
    renderStatusIndicator(status: string | null): JSX.Element;
    renderError(): JSX.Element;
}
